export default {
  modules: [
    'DisplaySize',
    'Toolbar',
    'Resize',
    'Delete',
  ],
  deleteText: 'Delete',
  overlayStyles: {
    position: 'absolute',
    boxSizing: 'border-box',
    border: '1px dashed #444',
  },
  handleStyles: {
    position: 'absolute',
    height: '12px',
    width: '12px',
    backgroundColor: 'white',
    border: '1px solid #777',
    boxSizing: 'border-box',
    opacity: '0.80',
  },
  displayStyles: {
    position: 'absolute',
    font: '12px/1.0 Arial, Helvetica, sans-serif',
    padding: '4px 8px',
    textAlign: 'center',
    backgroundColor: 'white',
    color: '#333',
    border: '1px solid #777',
    boxSizing: 'border-box',
    opacity: '0.80',
    cursor: 'default',
  },
  deleteBtnStyles: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate3d(-50%, -50%, 0)',
    fontSize: '12px',
    padding: '0 4px',
    height: '28px',
    lineHeight: '28px',
    background: '#000',
    color: '#fff',
    textAlign: 'center',
    borderRadius: '5px',

  },
  deleteArrowStyles: {
    position: 'absolute',
    display: 'block',
    top: '-12px',
    left: '50%',
    width: '0',
    height: '0',
    border: '6px solid #000',
    borderColor: 'transparent transparent #000 transparent',
    transform: 'translate3d(-50%, 0, 0)',
  },
  toolbarStyles: {
    position: 'absolute',
    top: '-12px',
    right: '0',
    left: '0',
    height: '0',
    minWidth: '100px',
    font: '12px/1.0 Arial, Helvetica, sans-serif',
    textAlign: 'center',
    color: '#333',
    boxSizing: 'border-box',
    cursor: 'default',
  },
  toolbarButtonStyles: {
    display: 'inline-block',
    width: '24px',
    height: '24px',
    background: 'white',
    border: '1px solid #999',
    verticalAlign: 'middle',
  },
  toolbarButtonSvgStyles: {
    fill: '#444',
    stroke: '#444',
    strokeWidth: '2',
  },
};
